all:
	cd vhr
	nohup /usr/bin/env /usr/lib/jvm/jdk-11.0.10/bin/java -Dfile.encoding=UTF-8 @/tmp/cp_2r1tqjzha8emheihcjv4ywvku.argfile org.javaboy.vhr.VhrApplication
	cd ../vuehr
	nohup npm run-script serve
